### ISSUE TITLE
Cross-Check CRUD API - woodo01

### ISSUE THREAD

**Issue by woodo01** [rolling-scopes-school/support#983]
**There is no cross-check scores at all because I have been expelled and restored.**

1. A link to your deployed project
    - not deployed
2. A link to the project repository on Github.
    - [link](https://github.com/woodo01/crud_api/pull/1)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/) CRUD API
5. A screenshot of cross-checking marks
<img width="808" alt="image" src="https://github.com/user-attachments/assets/74b8b212-fb55-4631-adeb-4ba528ce81a7">

6. A final score after self-assessment, with comments
Score: 222 / 222

Basic Scope

- [x]  The repository with the application contains a Readme.md file containing detailed instructions for installing, running and using the application (10/10)
- [x]  GET api/users implemented properly (10/10)
- [x]  GET api/users/{userId} implemented properly (10/10)
- [x]  POST api/users implemented properly (10/10)
- [x]  PUT api/users/{userId} implemented properly (10/10)
- [x]  DELETE api/users/{userId} implemented properly (10/10)
- [x]  Users are stored in the form described in the technical requirements (6/6)
- [x]  Value of port on which application is running is stored in .env file (6/6)

Advanced Scope

- [x]  Task implemented on Typescript (30/30)
- [x]  Processing of requests to non-existing endpoints implemented properly (10/10)
- [x]  Errors on the server side that occur during the processing of a request should be handled and processed properly (10/10)
- [x]  Development mode: npm script start:dev implemented properly (10/10)
- [x]  Production mode: npm script start:prod implemented properly (10/10)

Hacker Scope

- [x] There are tests for API (not less than 3 scenarios) (30/30)
- [x]  There is horizontal scaling for application with a load balancer (50/50)
7. A cross-check score of your Score 
0

**Comment by solidados** [comment]
# Task Implementation Assessment
Total Score after assessment: **212** of **222**

## Отзыв по пунктам ТЗ:
#### Частично выполненные пункты:
1) The repository with the application contains a `Readme.md` file containing detailed instructions for installing, running and using the application  
#### Отзыв:  
Readme does not contain endpoints or any explanations "where to go" after application started  

2) Production mode: npm script `start:prod` implemented properly  
#### Отзыв:  
- All necessary plugin installations performed.  
- starting either `$ npm run start:prod` or simply: `$ webpack` with all necessary options or commands return as follows:  
> [webpack-cli] Unable load '..../crud_api/webpack.config.ts'  
> [webpack-cli] Unable to use specified module loaders for ".ts"  
> [webpack-cli] Cannot find module 'ts-node/register' from '..../crud_api'  
> [webpack-cli] Cannot find module 'sucrase/register/ts' from '..../crud_api'  
> [webpack-cli] Cannot find module '@babel/register' from '..../crud_api'  
> [webpack-cli] Cannot find module 'esbuild-register/dist/node' from '..../crud_api'  
> [webpack-cli] Cannot find module '@swc/register' from '..../crud_api'  
> [webpack-cli] Please install one of them

### Выполненные пункты:
1) GET `api/users` implemented properly 
2) GET `api/users/{userId}` implemented properly 
3) POST `api/users` implemented properly 
4) PUT `api/users/{userId}` implemented properly 
5) DELETE `api/users/{userId}` implemented properly 
6) Users are stored in the form described in the technical requirements 
7) Value of port on which application is running is stored in `.env` file 
8) Task implemented on Typescript 
9) Processing of requests to non-existing endpoints implemented properly 
10) Errors on the server side that occur during the processing of a request should be handled and processed properly 
11) Development mode: npm script `start:dev` implemented properly 
12) There are tests for API (not less than 3 scenarios) 
13) There is horizontal scaling for application with a load balancer
